internal/api/room/control.go
internal/http/logger.go
internal/session/manager.go
internal/session/session.go
internal/websocket/filechooserdialog.go
internal/websocket/handler/control.go
internal/websocket/handler/system.go
internal/websocket/manager.go
pkg/types/session.go

When user disconnects from WebSocket, it is immediately propagated as disconnect and he loses control. We should try to distinguish between natural close event (user left) and temporary close event (network issues) and give some chance to the user to re-establish connection before we announce it as disconnected.

Temporary websocket disconnect handling

---

pkg/gst/gst.c
pkg/gst/gst.go
pkg/gst/gst.h
pkg/types/capture.go

Adding object set to gstreamer API:
- set integer (encoding bitrate)
- set caps framerate
- set caps resolution

Gstreamer - add object set to API.

---

internal/desktop/drop.go
pkg/drop/drop.c
pkg/gst/gst.c
pkg/gst/gst.go
pkg/gst/gst.h

Since v1.5.2 drop upload did not work.
```
(neko:793): Gtk-CRITICAL **: 19:15:55.437: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
```
```
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
```
```
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
neko: ../../src/xcb_io.c:725: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
* Adding gst main loop seems to have created deadlock in `gtk_init` function.
* `kataras/go-events@v0.0.3` version contains bug, so `finished` handler for `Once` event listener got bad type …

Fix drop upload

---

internal/webrtc/track.go

We do not need to (and should not) move user from - to the same stream beacuse it is 1) pointless and 2) creates deadlock.

Fix duplicate stream request

---

internal/http/batch.go
internal/http/manager.go
openapi.yaml

Add a single endpoint `/api/batch` that can accept array of multiple requests and executes them.
```bash
curl -X POST http://127.0.0.1:3000/api/batch --data '[{"path":"/api/whoami", "method":"GET"},{"path":"/api/batch", "method":"GET"},{"path":"/api/whoami", "method":"GET"}]' | jq
```

Add batch endpoint

---

pkg/xorg/xorg.c
pkg/xorg/xorg.h

Currently non-existing keys were mapped to a single keycode, usually `200`. This posed a problem if multiple keysyms have been pressed simultaneously, since they all shared a single keycode.
<del>New approach tries to get all free keycodes, puts them to a circular list. Each time when a new keycode is needed, the next free keycode is taken. Once they all get used, it repeats.<*del>
<del>If there is no free keycode available, we use last two anyway. It might be assigned for something different, but we reassign when needed.</del>
Worked in most cases but it did not respect modifiers, therefore code has been changed to Xkb implementation from TigerVNC. Known limitation is, that when all keycodes are used, they do not work anymore.
Memory leak from `XGetKeyboardMapping` function, its returned …

Fix free keycodes maping

---

internal/webrtc/handler.go
internal/webrtc/manager.go
internal/webrtc/payload/receive.go
internal/webrtc/payload/send.go

Implementing simple ping protocol, that only adds current timestamp to a message and sends it back. This allows client to calculate latency.

WebRTC ping over data channel

---

internal/webrtc/manager.go

For renegotiation, iOS fails with `Failed to set SSL role for the transport.`. 
https://stackoverflow.com/questions/34095194/web-rtc-renegotiation-errors

Set answering DTLS role as server.

---

pkg/gst/gst.c
pkg/gst/gst.go
pkg/gst/gst.h

By calling this function, we force gstreamer that next sample will be keyframe.
Checking if it really is keyframe can be done (for VP8) with:
```go
isKeyFrame := sample.Data[0]&0x07 == 0
if isKeyFrame {
logger.Info().Msg("webrtc keyframe")
}
```
Has only been tested with VP8.

Gst: Emit video keyframe on demand.

---

Dockerfile
Dockerfile.nvidia
internal/api/room/screen.go
internal/capture/manager.go
internal/desktop/manager.go
internal/desktop/xorg.go
internal/websocket/handler/screen.go
internal/websocket/handler/system.go
pkg/types/capture.go
pkg/types/desktop.go
pkg/xorg/xorg.c
pkg/xorg/xorg.go
pkg/xorg/xorg.h
runtime/xdummy-randr.patch

Currently only modelines specified in xorg prior start specified what resolutions can the screen have. With this PR, this constraint is removed and modelines are added on demand. They are rounded to 8, therefore you shold get the nearest size from your requested.

Custom sizes with XRandR

---

internal/capture/streamsink.go
internal/config/capture.go
internal/webrtc/track.go
pkg/gst/gst.c
pkg/gst/gst.go
pkg/gst/gst.h
pkg/types/capture.go
pkg/types/codec/codecs.go

Adding keyframe lobby to stream sink, meaning that when we switch between streams, listener goes first to a keyframe lobby, a keyframe will be requested from gstreamer pipeline, and once it arrives it will be sent to the listener.
Gstreamer tells us by identifying `delta_unit` for each sample. If sample is delta unit, it means it cannot be decoded independently. If it is not delta unit, that means we have keyframe.
This reduces unwanted artifacts and allows fast joining to a new pipeline.

Wait for keyframe on switching streams

---

internal/webrtc/manager.go
internal/webrtc/track.go

https://chromium.googlesource.com/external/webrtc/+/master/modules/pacing/g3doc/index.md
> The paced sender solves this by having a buffer in which media is queued, and then using a leaky bucket algorithm to pace them onto the network.
This has been implemented with the new GCC estimator. It is not suitable for ultra real time usecases, because it creates insane delays.
Additionaly, number of RTCP reports increased after configuring TWCC header extension sender, so optimizaition has been done.

GCC No-Op Pacer

---

internal/capture/streamsink.go
internal/webrtc/track.go

Before we only short-circuited emitting samples to the user, instead of unsubscribing the pipeline. But since we implemented keyframe lobby for streamsink, we want to use it as well here and switch only on keyframe to avoid showing artifacts.
Reimplmeneting this code has been considered as unnecessary, therefore this concept was switched to subscribing & unsubscribing each pipeline on pause events. We also needed to ensure, keyframe request won't be spamming pipeline. Therefore only first keyframe request is forwarded to the pipeline until we recive keyframe.

Switch to listeners for webrtc pause

---

internal/config/webrtc.go
internal/webrtc/manager.go
internal/websocket/handler/signal.go

Give ability to toggle estimator in config. If it is turned off, it shall not intercept in any way with current code. Client shall be notified, even if asking for `video_auto: true` he gets `video_auto: false`.

Toggle estimator config

---

internal/config/webrtc.go
internal/webrtc/manager.go
internal/webrtc/metrics.go
pkg/types/codec/codecs.go

There should be possibility to start bandwidth estimator passively, meaning it would be enabled and estimate bandwidth to metrics, but never actually changing any pipeline.

Passive bandwidth estimator option

---

Dockerfile
Dockerfile.nvidia

Removing the need for `~/.config/pulse/client.conf` file by adding `PULSE_SERVER` env variable.

Configure pulseaudio from env

---

internal/websocket/manager.go
internal/websocket/peer.go

Docker log line can be up to 16k long, so we want to limit very long payloads for websockets.

Set max payload log size for WebSockets

---

internal/webrtc/cursor/image.go
internal/webrtc/cursor/position.go
internal/webrtc/handler.go
internal/webrtc/manager.go
internal/webrtc/metrics.go
internal/webrtc/payload/receive.go
internal/webrtc/payload/send.go
internal/webrtc/peer.go
internal/webrtc/track.go
internal/websocket/handler/signal.go
pkg/types/webrtc.go

- Removed anonymous functions in webrtc, moved them to webrtc peer.
- Refactor metrics - with session context, with collector functions.
- Refactor cursor images & position - use interface instead of pointer to function, rw mutex for listeners.
- Cursor images - fix invalid cache serial race condition, rw mutex for cache.
- Do not include header in data messages - no need to parse them twice.
- Fixed an error, where stream would not be cleared if video was paused.
- Fixed an error, where RTCP reader goroutine for audio could leak.
- And other minor changes...

WebRTC refactor, pt.1

---

internal/session/manager.go
internal/session/session.go
internal/websocket/manager.go
internal/websocket/peer.go
pkg/types/session.go

Previously webrtc and websocket peers were created similarly. But websocket has been refactored in the meantime and has slightly different connection flow that webrtc. The functions should reflect that.

Refactor websocket session sync

---

internal/config/desktop.go
internal/desktop/manager.go
pkg/xevent/xevent.c
pkg/xevent/xevent.go
pkg/xevent/xevent.h
pkg/xorg/xorg.c

When going fullscreen, resizing screen and then exiting fullscreen, original window is misplaced. This issue happend for `openbox` and `metacity` window managers. `ratpoison` or not using wm at all does not  cause this issue.
According to https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#id2731936:
> _NET_WM_STATE_FULLSCREEN indicates that the window should fill the entire screen and have no window decorations. Additionally the **Window Manager is responsible for restoring the original geometry after a switch from fullscreen back to normal window**. For example, a presentation program would use this hint.
Window Manager should be the one to restore the window properly, but it does not. Therefore we listen to `_NET_WM_STATE_FULLSCREEN` events, and when the screen was changed …

Error when changing resolution while fullscreen + unminimize

---

internal/api/room/control.go
internal/config/session.go
internal/session/manager.go
internal/websocket/handler/control.go
openapi.yaml
pkg/types/session.go

So that we can toggle globally if users should have locked or unlocked controls. Only admins can modify this and it won't affect them.

Add locked controls to settings

---

internal/api/router.go
internal/api/session.go
internal/session/session.go
openapi.yaml
pkg/types/session.go

Add `/api/sessions` endpoint, so that we can get information about who is currently in the room.
Add `watching_since`, `not_watching_since`, `connected_since` and `not_connected_since` to state so that we know when the state changed the last time.
This information can be used by the external system to determine:
- how many people (admins and/or users) are currently connected
- when the last person (admin and/or user) disconnected
- are the connected persons actually watching?
This is an attempt to have similar (but more granular) functionality as `last_admin_left_at` and `last_user_left_at` from m1k1o/neko's `/stats` endpoint.

Add stats for state

---

internal/api/room/upload.go
internal/webrtc/peer.go
internal/websocket/manager.go
internal/websocket/peer.go

| error | comment |
| ----- | ------- |
| `send message error` | -> WARN |
| `request failed (502): *` | _unchanged_ |
| `request failed (500): unable to copy uploaded file to destination file` | If no files received, should be `Bad Request` -> WARN. |
| `read message error` | -> WARN |
| `peer connection destroyed` | `dtls fatal: conn is closed`: do not close webrtc if already closed |
| `mux: ending readLoop dispatch error io: read/write on closed pipe` and `Incoming unhandled RTP ssrc(*), OnTrack will not be fired. mid RTP Extensions required for Simulcast` | error from pion codebase |
| `error while processing websocket event` | _unchanged_, relevant error from client |
| `error getting candidate pairs stats the agent is closed` | error from pion codebase, seen only when shutting down …

Fix noisy errors

---

internal/webrtc/manager.go
internal/webrtc/peer.go
internal/webrtc/track.go
internal/websocket/handler/handler.go
internal/websocket/handler/signal.go
pkg/types/capture.go
pkg/types/event/events.go
pkg/types/message/messages.go
pkg/types/webrtc.go

Split signaling for video and audio to requests and resonses. Now, we can request any stream using stream selector. We can also disable video and/or audio when requesting.
Added new `signal/audio` that allows futher manipulation of audio track in webrtc.

Refactor signaling for video and audio

---

internal/api/room/keyboard.go
internal/desktop/xorg.go
internal/webrtc/handler.go
internal/webrtc/payload/receive.go
internal/websocket/handler/control.go
internal/websocket/handler/handler.go
internal/websocket/handler/keyboard.go
openapi.yaml
pkg/types/desktop.go
pkg/types/message/messages.go
pkg/xorg/xorg.c
pkg/xorg/xorg.go
pkg/xorg/xorg.h

Currently we only use `NumLock` and `CapsLock` as xorg modifiers. We should extend it to support all modifiers:
| Const Name    | Comment  |
| ------------- | -------- |
| `ShiftMask`   | Shift    |
| `LockMask`    | CapsLock |
| `ControlMask` | Control  |
| `Mod1Mask`    | Alt      |
| `Mod2Mask`    | NumLock  |
| `Mod3Mask`    | Meta     |
| `Mod4Mask`    | Super    |
| `Mod5Mask`    | AltGr    |
Source: https://tronche.com/gui/x/xlib/events/keyboard-pointer/keyboard-pointer.html
One prominent use-case for those modifiers is new `Scroll` support for `ControlKey`. That means, when someone is scrolling, they can tell together with scroll event if control key should be activated. This reflects the behavior of javascript wheel event.

Add Xorg modifiers

---

internal/config/member.go
internal/member/file/provider.go
internal/member/file/types.go

Passwords in members file provider should be sha256 hashed and not stored in plaintext. Leaving config option for backwards compatibility, but the default is changing to true for security.

Members hash passwords

---

internal/desktop/manager.go
pkg/xevent/xevent.c
pkg/xevent/xevent.go
pkg/xevent/xevent.h

If X11 throws an error during screen config get/set, the default error handler at the time will be one which causes a program exit. This splits the error handler registration in xevent into its own call, allowing us to register our error handler earlier on. This results in the safe error handling logic actually being called instead of a full program exit.

Move X11 error handler registration to before screen sets
